[package]
name = "rs_unimrcp_recog"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.147"
env_logger = "0.10.0"
log = "0.4.19"

[build-dependencies]
bindgen = "0.66.1"
